name: Publish
on:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pgjones/actions/build@dbbee601c084d000c4fc711d4b27cb306e15ead1 # v1

  pypi-publish:
    needs: ['build']
    environment: 'publish'

    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        with:
          packages-dir: artifact/
